# Lecture 5. Linear Algebra
### adapted from http://cs229.stanford.edu/section/cs229-linalg.pdf

## Linear algebra: a compact way to represent and operate on sets of linear equations

$$
\begin{array}{ccc}
4x_1 & − & 5x_2 & = &−13 \\
−2x_1 & + & 3x_2 & = & 9
\end{array}$$
  
$$ Ax = b $$
 
$$A = \left[ \begin{array}{cc} 4 & -5
\\-2 & 3   \end{array} \right] , 
b = \left[ \begin{array}{c} -13 
\\9 \end{array} \right]$$

## Basic notation
![](assets/Lecture_5_text-497ae026.png)

In [1]:
import numpy as np
A=np.array([[1,2,3],[4,5,6]])
A[1,2]

6

In [2]:
a = np.array([1,2,3])
a.T
a[2]

3

![](assets/Lecture_5_text-34cbc671.png)

![](assets/Lecture_5_text-018775c9.png)

In [3]:
A[:,0]
A[1,:] #in python you can simply use A[1]

array([4, 5, 6])

## Element-wise Matrix product (Hadamard)
For $A,B \in \mathbb{R}^{m\times n}$

$C = A*B$ 

$C_{ij}=A_{ij}B_{ij}$

### Exercise compute A*A using two for loops

A = np.random.random((2,3))

C = np.zeros((2,3))

In [4]:
A=np.array([[1,2,3],[4,5,6]])
AA = np.empty(A.shape)
for i in range(A.shape[0]):
  for j in range(A.shape[1]):
     AA[i,j] = A[i,j]*A[i,j]

np.sum(np.abs(AA-A*A))

0.0

## Poll quiz 1

## Matrix multiplication
![](assets/Lecture_5_text-6562178e.png)

In [5]:
# implement with for loops the matrix multiplication A@B
# with two random matrices.
import numpy as np
A = np.random.random((2,3))
B = np.random.random((3,4))
AB = np.zeros((A.shape[0],B.shape[1]))
for i in range(A.shape[0]):
  for j in range(B.shape[1]):
    for k in range(A.shape[1]):
      AB[i,j] +=  A[i,k]*B[k,j]

np.sum(np.abs(AB-A@B))

0.0

## Vector-vector products
![](assets/Lecture_5_text-5e5f73cf.png)  

### Implement the vector-vector product without using @ 

In [6]:
a = np.random.random((3,))
b = np.random.random((3,))
c = np.zeros((3,))

for n in range(len(a)):
    c += a[n]*b[n]

print(np.sum(np.abs(c-a@b)))
print(np.sum(np.abs(c-np.inner(a,b))))

0.0
0.0


![](assets/Lecture_5_text-875660a3.png)

In [7]:
a = np.random.random((3,))
b = np.random.random((4,))
print(a.shape)
print(b.shape)
rows, cols = (len(a), len(b))
c = np.zeros((rows,cols))

for r_ in range(rows):
    for c_ in range(cols):
        c[r_,c_] = a[r_]*b[c_]

print(np.sum(np.abs(c-np.outer(a,b))))

(3,)
(4,)
0.0


In [8]:
a = np.random.random((3,1))
b = np.random.random((1,4))
print(a.shape)
print(b.shape)
# example of broadcasting
print(np.sum(np.abs(a@b-np.outer(a,b))))

(3, 1)
(1, 4)
0.0


### create two random column vectors of length 3
* compute their inner product with one for loop
* compute their outer product with two for loops
* compute the outer product using the @ symbol alone

In [36]:
# create two random length 3 column vectors
a=np.random.random((1,3))
b=np.random.random((1,3))
ab=0



In [37]:
# compute their inner product
for i in range(0,a.shape[1]):
    ab+=a[0][i]*b[0][i] 
    
ab-np.inner(a,b)

array([[0.]])

In [39]:
# compute their outer product with for loops
AB=np.zeros((3,3))
for i in range(0,a.shape[1]):
    for j in range(0,b.shape[1]):
        AB[i,j]=a[0][i]*b[0][j]
AB-np.outer(a,b)

In [44]:
#computer their outer product using @
outer=a.T@b
outer-np.outer(a,b)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

![](assets/Lecture_5_text-d0cef9bc.png)

In [9]:
a = [1,2,3]
np.outer(a,[1,1,1])

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

## Quiz number 4

In [11]:
import numpy as np
a = np.random.random((3,))
print(a.T@a)
print(np.linalg.norm(a, ord=2))
print(np.linalg.norm(a, ord=2)**2)


1.215393920429561
1.1024490557071382
1.2153939204295607


## Matrix-vector products
![](assets/Lecture_5_text-7f3aa5f7.png)
![](assets/Lecture_5_text-95ec9688.png)
![](assets/Lecture_5_text-cf1e838d.png)

In [10]:
A = np.random.random((3,4))
x = np.random.random((4,))
y = np.zeros( A.shape[0])

for n in range(A.shape[0]):
        y[n] = A[n,:]@x
            
print( np.sum( np.abs( y - A@x ) ) )            
    

3.3306690738754696e-16


In [11]:
y = np.zeros( A.shape[0])

for n in range(A.shape[1]):
        y += A[:,n]*x[n]
            
print( np.sum( np.abs( y - A@x ) ) )            
    

3.3306690738754696e-16


* A columns, B rows
![](assets/Lecture_5_text-4da76187.png)
AB is equal to the sum, over all i, of the outer product of the i-th column of A and the i-th row of B. Difficult expression.

In [12]:
A = np.random.random((3,4))
B = np.random.random((4,5))
row, cols = (A.shape[0],B.shape[1])
C = np.zeros((row, cols))

for n in range(A.shape[1]):
        C += np.outer(A[:,n],B[n,:])
            
print( np.sum( np.abs( C - A@B ) ) )            
    

1.2212453270876722e-15


### Properties of multiplication
![](assets/Lecture_5_text-3ce7133e.png)

## Operations and properties of matrices

### Identity matrix
![](assets/Lecture_5_text-e988a518.png)

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Diagonal Matrix
![](assets/Lecture_5_text-0e346bb7.png)

In [14]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

![](assets/Lecture_5_text-cfe28662.png)
![](assets/Lecture_5_text-37b4bcaf.png)

In [15]:
T = np.repeat([[1,2,3]],repeats=3, axis=0)
print(T)
print('******')
print(T.T)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
******
[[1 1 1]
 [2 2 2]
 [3 3 3]]


### Inverse of a matrix
![](assets/Lecture_5_text-ff6ad71f.png)

* A is **invertible** is $A^{-1}$ exists
* A is **non-invertible** otherwise

In [26]:
from numpy.linalg import inv
a = np.array([[1., 2.], [3., 4.]])
ainv = inv(a)
print(ainv)
np.allclose(np.dot(a, ainv), np.eye(2))
True
np.allclose(np.dot(ainv, a), np.eye(2))
True

[[-2.   1. ]
 [ 1.5 -0.5]]


True

### Properties of the inverse
![](assets/Lecture_5_text-944d0473.png)


### Symmetric matrices
![](assets/Lecture_5_text-57e7e745.png)

In [16]:
S = T+T.T
print(S)
print('****** SYMMETRIC *****')
print(S.T)

[[2 3 4]
 [3 4 5]
 [4 5 6]]
****** SYMMETRIC *****
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [17]:
AS = T-T.T
print(AS)
print('****** ANTI-SYMMETRIC *****')
print(AS.T)

[[ 0  1  2]
 [-1  0  1]
 [-2 -1  0]]
****** ANTI-SYMMETRIC *****
[[ 0 -1 -2]
 [ 1  0 -1]
 [ 2  1  0]]


### Trace of a matrix
![](assets/Lecture_5_text-1d8e4959.png)

# Quiz number 3

In [18]:
print(S)
print(np.trace(S))
print(AS)
print(np.trace(AS))

[[2 3 4]
 [3 4 5]
 [4 5 6]]
12
[[ 0  1  2]
 [-1  0  1]
 [-2 -1  0]]
0


### Properties of trace
![](assets/Lecture_5_text-13f536da.png)

### Norm of a vector 
![](assets/Lecture_5_text-531d34a1.png)
![](assets/Lecture_5_text-128b60f7.png)

In [19]:
from numpy.linalg import norm

print('**** L_2 **** ')
print(norm([1]))
print(norm([1,-2,3]))
print(norm([1,-2,3], ord=2))
print('**** L_1 **** ')
print(norm([1], ord=1))
print(norm([1,-2,3],  ord=1))
print('**** L_inf **** ')
print(norm([1], ord=np.inf))
print(norm([1,-2,3],  ord=np.inf))

**** L_2 **** 
1.0
3.7416573867739413
3.7416573867739413
**** L_1 **** 
1.0
6.0
**** L_inf **** 
1.0
3.0


### Norm of a Matrix

* ![](assets/Lecture_5_text-cfaf3402.png)

* $L_1$ matrix norm of a matrix is equal to the maximum of $L_1$ norm of a column of the matrix.

In [20]:
from numpy.linalg import norm

print('**** FROEBINIUS NORM **** ')
print(norm([[1,2,3],
            [4,5,6]], ord='fro'))
print('**** L_1 NORM **** ')
print(norm([[1,2,3],
            [4,5,6]], ord=1))
#help(norm)

**** FROEBINIUS NORM **** 
9.539392014169456
**** L_1 NORM **** 
9.0


# Quiz number 4

## Gradient of a Matrix
![](assets/Lecture_5_text-a5bde8f6.png)
![](assets/Lecture_5_text-aff74ac9.png)


### Concept of derivative
![](assets/Lecture_5_text-31c50a77.png)
http://xaktly.com/TheDerivative.html

### Concept of gradient
![](assets/Lecture_5_text-a5e0b340.png)
https://ozzieliu.com/2016/02/09/gradient-descent-tutorial/